package com.example.trading.portfolio.conviction;

import java.time.LocalDate;
import java.util.List;

/** API DTOs for Conviction & Thesis Tracking (SPEC.md §6). */
public final class ConvictionDto {

    private ConvictionDto() {}

    /** Upsert request. */
    public record UpsertRequest(
            String symbol,
            String thesis,
            int convictionScore,
            Integer holdingHorizonMonths,
            String invalidationTriggers,
            Double purchaseMultibaggerScore, // optional; if null, service looks up latest multibagger score
            LocalDate purchaseDate
    ) {}

    /** Drift view for one holding. */
    public record ConvictionDrift(
            String symbol,
            String thesis,
            int convictionScore,
            Integer holdingHorizonMonths,
            String invalidationTriggers,
            LocalDate purchaseDate,
            Double purchaseMultibaggerScore,
            Double currentMultibaggerScore,
            Double driftPoints,
            String status, // INTACT | UNDER_REVIEW | BROKEN | NO_CURRENT_SCORE
            boolean thesisStated,   // false = generated by the app, not written by the investor (B-097)
            String holdingSymbol    // the symbol the active holding is filed under, when it differs
    ) {}

    /**
     * Aggregate view over the <em>active</em> holdings (B-097).
     *
     * <p>{@code intactCount}, {@code underReviewCount} and {@code brokenCount} count only theses
     * the investor wrote. A generated record appears in {@code drifts} with
     * {@code thesisStated=false} and is counted in {@code seededCount}; a holding with no record
     * at all is in {@code holdingsMissingThesis}. Records for exited stocks are kept in the table
     * but left out of every figure here.
     *
     * @param totalHoldings   active holdings, not conviction rows
     * @param statedCount     holdings with a thesis the investor wrote
     * @param seededCount     holdings whose only thesis was generated by the app
     */
    public record ConvictionReport(
            int totalHoldings,
            int intactCount,
            int underReviewCount,
            int brokenCount,
            List<ConvictionDrift> drifts,
            List<String> holdingsMissingThesis,
            int statedCount,
            int seededCount,
            List<String> holdingsWithSeededThesis
    ) {}
}
