package com.example.trading.portfolio.conviction;

import com.example.trading.persistence.HoldingsEntity;
import com.example.trading.persistence.HoldingsRepository;
import com.example.trading.persistence.MultibaggerScoreEntity;
import com.example.trading.persistence.MultibaggerScoreRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

/**
 * Conviction & Thesis Tracking (SPEC.md §6). Computes "thesis drift" as the delta between
 * the multibagger composite score at purchase and the latest screening score.
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class ConvictionService {

    public static final String STATUS_INTACT = "INTACT";
    public static final String STATUS_UNDER_REVIEW = "UNDER_REVIEW";
    public static final String STATUS_BROKEN = "BROKEN";
    public static final String STATUS_NO_CURRENT = "NO_CURRENT_SCORE";

    private final HoldingConvictionRepository repository;
    private final MultibaggerScoreRepository multibaggerRepository;
    private final HoldingsRepository holdingsRepository;
    private final ConvictionConfig config;

    /** Investor-supplied upsert: the horizon in the request is a statement of intent. */
    @Transactional
    public HoldingConvictionEntity upsert(ConvictionDto.UpsertRequest req) {
        return upsert(req, true);
    }

    /**
     * @param horizonStated false for auto-generated records, whose 24-month horizon is a seed value
     *                      rather than the investor's choice. An existing stated horizon is never
     *                      downgraded to "seeded" by a later auto-generation pass.
     */
    @Transactional
    public HoldingConvictionEntity upsert(ConvictionDto.UpsertRequest req, boolean horizonStated) {
        HoldingConvictionEntity entity = repository.findBySymbol(req.symbol())
                .orElseGet(() -> HoldingConvictionEntity.builder().symbol(req.symbol()).build());

        entity.setThesis(req.thesis());
        entity.setConvictionScore(req.convictionScore());
        entity.setHoldingHorizonMonths(req.holdingHorizonMonths());
        if (horizonStated || entity.getHorizonStated() == null) {
            entity.setHorizonStated(horizonStated);
        }
        // B-097: the investor path always marks the thesis as stated; the seeding path never
        // downgrades one the investor wrote.
        if (horizonStated || entity.getThesisStated() == null) {
            entity.setThesisStated(horizonStated);
        }
        entity.setInvalidationTriggers(req.invalidationTriggers());
        entity.setPurchaseDate(req.purchaseDate());
        entity.setPurchaseMultibaggerScore(req.purchaseMultibaggerScore() != null
                ? req.purchaseMultibaggerScore()
                : latestScoreFor(req.symbol()));

        HoldingConvictionEntity saved = repository.save(entity);
        log.info("Conviction: upserted {} (conviction={}, purchase score={})",
                saved.getSymbol(), saved.getConvictionScore(), saved.getPurchaseMultibaggerScore());
        return saved;
    }

    public ConvictionDto.ConvictionDrift getDrift(String symbol) {
        HoldingConvictionEntity c = repository.findBySymbol(symbol)
                .orElseThrow(() -> new IllegalArgumentException("No conviction record for " + symbol));
        return buildDrift(c);
    }

    /**
     * The report over the <em>active</em> holdings only, joined to conviction rows across
     * exchange prefixes (B-097, Gotcha 84).
     *
     * <p>Before this it reported every row in the table: 46 rows for 29 holdings, 17 of them
     * for stocks already sold, and 45 of the 46 theses generated by the app. It then listed
     * {@code BSE:HINDALCO} as "missing a thesis" while the one real thesis sat under
     * {@code NSE:HINDALCO}. Counts here are over stated theses; a generated one is neither
     * intact nor broken, it is unwritten.
     */
    public ConvictionDto.ConvictionReport getReport() {
        java.util.Map<String, HoldingConvictionEntity> bySymbol = repository.findAll().stream()
                .collect(Collectors.toMap(HoldingConvictionEntity::getSymbol, c -> c, (a, b) -> a));

        List<ConvictionDto.ConvictionDrift> drifts = new ArrayList<>();
        List<String> missing = new ArrayList<>();
        List<String> seeded = new ArrayList<>();
        int intact = 0, underReview = 0, broken = 0, stated = 0;
        List<HoldingsEntity> active = holdingsRepository.findActive();
        for (HoldingsEntity h : active) {
            HoldingConvictionEntity c = null;
            for (String candidate : com.example.trading.holdings.SymbolVariants.candidates(h.getSymbol())) {
                c = bySymbol.get(candidate);
                if (c != null) break;
            }
            if (c == null) {
                missing.add(h.getSymbol());
                continue;
            }
            ConvictionDto.ConvictionDrift d = buildDrift(c, h.getSymbol());
            drifts.add(d);
            if (!d.thesisStated()) {
                seeded.add(h.getSymbol());
                continue;
            }
            stated++;
            switch (d.status()) {
                case STATUS_INTACT -> intact++;
                case STATUS_UNDER_REVIEW -> underReview++;
                case STATUS_BROKEN -> broken++;
                default -> { }
            }
        }
        missing.sort(String::compareTo);
        seeded.sort(String::compareTo);
        return new ConvictionDto.ConvictionReport(active.size(), intact, underReview, broken, drifts,
                missing, stated, seeded.size(), seeded);
    }

    /**
     * Whether the thesis on a record was written by the investor. The stored flag wins; a legacy
     * row without one is read from what the seeding code writes - its text prefix and the
     * seeded-horizon marker. A default is not a statement (Gotcha 68).
     */
    static boolean isStated(HoldingConvictionEntity c) {
        if (c.getThesisStated() != null) return c.getThesisStated();
        if (Boolean.FALSE.equals(c.getHorizonStated())) return false;
        String t = c.getThesis() == null ? "" : c.getThesis().trim();
        return !t.isEmpty() && !t.startsWith(SEEDED_PREFIX);
    }

    /** Every generated thesis starts with this, which is how a legacy row is recognised. */
    static final String SEEDED_PREFIX = "Selected via app";

    /**
     * Auto-seed thesis records for holdings that don't have one yet, using the app's
     * existing multibagger screening history as the source of "why this stock was selected".
     *
     * <p>For each missing holding:
     * <ul>
     *   <li>Uses the latest multibagger score (if any) to derive grade, verdict, and key factors.</li>
     *   <li>Uses the earliest score as the drift baseline (so future changes show real movement).</li>
     *   <li>Maps composite score to conviction score (85+ → 9, 75+ → 8, …).</li>
     *   <li>Falls back to a placeholder thesis for holdings not yet screened.</li>
     * </ul>
     */
    /**
     * Re-runs auto-seed for (a) holdings with no conviction record yet, and
     * (b) existing records still sitting on a placeholder (identified by null
     * {@code purchaseMultibaggerScore}). Preserves any thesis the user has written
     * by hand — those have a non-null purchase score.
     */
    @Transactional
    public java.util.Map<String, Object> autoSeedFromDiscovery() {
        java.util.Map<String, HoldingConvictionEntity> existingBySymbol = repository.findAll().stream()
                .collect(Collectors.toMap(HoldingConvictionEntity::getSymbol, c -> c));

        List<HoldingsEntity> candidates = holdingsRepository.findAll().stream()
                .filter(h -> {
                    HoldingConvictionEntity existing = existingBySymbol.get(h.getSymbol());
                    // process if no record OR record is still a placeholder (null baseline score)
                    return existing == null || existing.getPurchaseMultibaggerScore() == null;
                })
                .toList();

        int seededWithScore = 0;
        int seededPlaceholder = 0;
        int upgradedFromPlaceholder = 0;
        for (HoldingsEntity h : candidates) {
            boolean isUpgrade = existingBySymbol.containsKey(h.getSymbol());
            List<MultibaggerScoreEntity> history = multibaggerRepository.findHistoryBySymbol(h.getSymbol());
            if (history.isEmpty()) {
                upsert(placeholderRequest(h), false);   // 24 months is a seed, not a statement
                if (!isUpgrade) seededPlaceholder++;
            } else {
                upsert(thesisFromMultibagger(h, history), false);   // seeded horizon
                if (isUpgrade) upgradedFromPlaceholder++;
                else seededWithScore++;
            }
        }
        log.info("Conviction: auto-seed — {} new from multibagger, {} new placeholders, {} upgraded from placeholder",
                seededWithScore, seededPlaceholder, upgradedFromPlaceholder);
        return java.util.Map.of(
                "processed", candidates.size(),
                "seededWithMultibaggerScore", seededWithScore,
                "upgradedFromPlaceholder", upgradedFromPlaceholder,
                "stillPlaceholder", seededPlaceholder,
                "manualThesisPreserved", existingBySymbol.size()
                        - (seededWithScore + upgradedFromPlaceholder + seededPlaceholder));
    }

    private ConvictionDto.UpsertRequest thesisFromMultibagger(HoldingsEntity h, List<MultibaggerScoreEntity> history) {
        MultibaggerScoreEntity latest = history.get(0);
        MultibaggerScoreEntity earliest = history.get(history.size() - 1);

        String thesis = String.format(
                "Selected via app's multibagger screening. Current grade %s (score %d/100, %s). " +
                "Earliest screen on %s at score %d. Key drivers: %s.",
                latest.getGrade(), latest.getCompositeScore(), humanVerdict(latest.getVerdict()),
                earliest.getScreeningDate(), earliest.getCompositeScore(),
                summarizeDrivers(latest));

        String invalidation = String.format(
                "Grade drops to C or below; composite score falls %s; verdict turns to MONITOR or AVOID; "
                + "bearish factors outweigh bullish (%s).",
                pointsBelow(latest.getCompositeScore(), 20),
                latest.getBearishFactors() != null && !latest.getBearishFactors().isBlank()
                        ? "current: " + truncate(latest.getBearishFactors(), 100) : "currently none flagged");

        java.time.LocalDate purchaseDate = earliest.getScreeningDate();
        if (h.getPurchaseDate() != null) {
            // Use actual purchase date if broker provided one — score at that date as baseline
            purchaseDate = h.getPurchaseDate().toLocalDate();
        }

        return new ConvictionDto.UpsertRequest(
                h.getSymbol(),
                thesis,
                convictionFromScore(latest.getCompositeScore()),
                24, // default 2-year horizon for multibagger plays
                invalidation,
                (double) earliest.getCompositeScore(),
                purchaseDate);
    }

    private ConvictionDto.UpsertRequest placeholderRequest(HoldingsEntity h) {
        java.time.LocalDate purchaseDate = h.getPurchaseDate() != null
                ? h.getPurchaseDate().toLocalDate() : java.time.LocalDate.now();
        String thesis = "Selected via app's discovery reports. Awaiting next weekly multibagger screen "
                + "for a detailed composite score — refine this thesis once available.";
        return new ConvictionDto.UpsertRequest(
                h.getSymbol(), thesis, 5, 24,
                "Grade turns weak (C or below) or app flags as AVOID.",
                null, purchaseDate);
    }

    private int convictionFromScore(int composite) {
        if (composite >= 85) return 9;
        if (composite >= 75) return 8;
        if (composite >= 65) return 7;
        if (composite >= 55) return 6;
        if (composite >= 45) return 5;
        if (composite >= 35) return 4;
        return 3;
    }

    private String humanVerdict(String verdict) {
        if (verdict == null) return "rated";
        return switch (verdict) {
            case "STRONG_MULTIBAGGER" -> "strong multibagger candidate";
            case "POTENTIAL_MULTIBAGGER" -> "potential multibagger";
            case "WATCHLIST" -> "watchlist-grade";
            case "MONITOR" -> "monitor-only";
            case "AVOID" -> "AVOID-rated";
            default -> verdict.toLowerCase().replace('_', ' ');
        };
    }

    private String summarizeDrivers(MultibaggerScoreEntity s) {
        List<String> top = new ArrayList<>();
        if (s.getTechnicalMomentumScore() >= 70) top.add("strong technical momentum");
        if (s.getVolumeAccumulationScore() >= 70) top.add("smart-money accumulation");
        if (s.getRelativeStrengthScore() >= 70) top.add("outperforming Nifty");
        if (s.getPriceStructureScore() >= 70) top.add("healthy price structure");
        if (s.getValuationScore() >= 70) top.add("attractive valuation");
        if (s.getInstitutionalInterestScore() >= 70) top.add("institutional buying");
        if (s.getSectorTailwindScore() >= 70) top.add("sector tailwind");
        if (top.isEmpty() && s.getBullishFactors() != null && !s.getBullishFactors().isBlank()) {
            return truncate(s.getBullishFactors(), 150);
        }
        if (top.isEmpty()) return "broad-based fundamentals";
        return String.join(", ", top);
    }

    private String pointsBelow(int currentScore, int drop) {
        int threshold = Math.max(0, currentScore - drop);
        return "below " + threshold;
    }

    private String truncate(String s, int max) {
        if (s == null) return "";
        return s.length() <= max ? s : s.substring(0, max - 1) + "…";
    }

    @Transactional
    public java.util.Map<String, Object> bulkUpsert(List<ConvictionDto.UpsertRequest> requests) {
        int created = 0;
        int failed = 0;
        List<String> errors = new ArrayList<>();
        for (ConvictionDto.UpsertRequest r : requests) {
            try {
                upsert(r);
                created++;
            } catch (Exception e) {
                failed++;
                errors.add(r.symbol() + ": " + e.getMessage());
            }
        }
        log.info("Conviction: bulk upsert — {} saved, {} failed", created, failed);
        return java.util.Map.of("saved", created, "failed", failed, "errors", errors);
    }

    private ConvictionDto.ConvictionDrift buildDrift(HoldingConvictionEntity c) {
        return buildDrift(c, null);
    }

    private ConvictionDto.ConvictionDrift buildDrift(HoldingConvictionEntity c, String holdingSymbol) {
        Double current = latestScoreFor(c.getSymbol());
        Double drift = (current != null && c.getPurchaseMultibaggerScore() != null)
                ? current - c.getPurchaseMultibaggerScore()
                : null;
        String status = classify(drift);
        return new ConvictionDto.ConvictionDrift(
                c.getSymbol(), c.getThesis(), c.getConvictionScore(),
                c.getHoldingHorizonMonths(), c.getInvalidationTriggers(),
                c.getPurchaseDate(), c.getPurchaseMultibaggerScore(), current, drift, status,
                isStated(c),
                holdingSymbol != null && !holdingSymbol.equals(c.getSymbol()) ? holdingSymbol : null);
    }

    private String classify(Double drift) {
        if (drift == null) return STATUS_NO_CURRENT;
        double drop = -drift; // drift is (current − purchase); positive drop = score went down
        if (drop >= config.getRedDriftThreshold()) return STATUS_BROKEN;
        if (drop >= config.getYellowDriftThreshold()) return STATUS_UNDER_REVIEW;
        return STATUS_INTACT;
    }

    private Double latestScoreFor(String symbol) {
        List<MultibaggerScoreEntity> history = multibaggerRepository.findHistoryBySymbol(symbol);
        return history.isEmpty() ? null : (double) history.get(0).getCompositeScore();
    }
}
